version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: esercitazioneod-mysql

    environment:
      MYSQL_ROOT_PASSWORD: dev_root_password
      MYSQL_DATABASE: esercitazioneod_db
      MYSQL_USER: esercitazioneod_user
      MYSQL_PASSWORD: dev_password

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: