// <auto-generated />
using EsercizioTecnicoOD.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsercizioTecnicoOD.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511100741_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EsercizioTecnicoOD.Core.Models.Commessa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Commesse");
                });

            modelBuilder.Entity("EsercizioTecnicoOD.Core.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Colore")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Modello")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Taglia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("EsercizioTecnicoOD.Core.Models.Job", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CommessaId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FaseDiLavorazione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StatoAvanzamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CommessaId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("EsercizioTecnicoOD.Core.Models.Item", b =>
                {
                    b.HasOne("EsercizioTecnicoOD.Core.Models.Job", "Job")
                        .WithOne("Item")
                        .HasForeignKey("EsercizioTecnicoOD.Core.Models.Item", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("EsercizioTecnicoOD.Core.Models.Job", b =>
                {
                    b.HasOne("EsercizioTecnicoOD.Core.Models.Commessa", "Commessa")
                        .WithMany("Jobs")
                        .HasForeignKey("CommessaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commessa");
                });

            modelBuilder.Entity("EsercizioTecnicoOD.Core.Models.Commessa", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("EsercizioTecnicoOD.Core.Models.Job", b =>
                {
                    b.Navigation("Item")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
